export default {
    host: 'https://portal.vistaapp.ir/api/',
    index: 'https://portal.vistaapp.ir/',
    messages: {
        server_error: 'مشکل در برقراری ارتباط با سرور. لطفا مجددا تلاش نمایید',
        successful: 'با موفقیت',
        phone_required: 'لطفا شماره تلفن را وارد نمایید',
        phone_not_valid: 'شماره تلفن وارد شده معتبر نمی باشد',
        mobile_required: 'لطفا شماره موبایل خود را وارد نمایید',
        mobile_not_valid: 'شماره موبایل وارد شده معتبر نمی باشد',
        email_not_valid: 'ایمیل وارد شده معتبر نمی باشد',
        address_required: 'لطفا آدرس خود را وارد نمایید',
        address_short: 'آدرس نمی تواند کمتر از 10 کاراکتر باشد',
        password_required: 'لطفا رمز عبور خود را وارد نمایید',
        password_short: 'رمز عبور نمی تواند کمتر از 6 کاراکتر باشد',
        password_not_match: 'رمز عبور و تکرار آن یکسان نیستند',
        user_updated: 'اطلاعات کاربری شما با موفقیت به روزرسانی گردید',
        website_title_required: 'لطفا عنوان وبسایت را وارد نمایید',
        preferred_domain_required: 'لطفا اولویت دامنه اول را وارد نمایید',
        preferred_domain_alternate_required: 'لطفا اولویت دامنه دوم را وارد نمایید',
        domain_url_required: 'لطفا آدرس وبسایت کارگزار دامنه را وارد نمایید',
        domain_username_required: 'لطفا نام کاربری کارگزار دامنه را وارد نمایید',
        domain_password_required: 'لطفا رمز عبور کارگزار دامنه را وارد نمایید',
        host_url_required: 'لطفا آدرس کارگزار هاست را وارد نمایید',
        host_username_required: 'لطفا نام کاربری کارگزار هاست  را وارد نمایید',
        host_password_required: 'لطفا رمز عبور کارگزار هاست را وارد نمایید',
        admin_url_required: 'لطفا آدرس پیشخوان وبسایت را وارد نمایید',
        admin_username_required: 'لطفا نام کاربری پیشخوان وبسایت  را وارد نمایید',
        admin_password_required: 'لطفا رمز عبور پیشخوان وبسایت را وارد نمایید',
        website_saved: 'وبسایت شما با موفقیت ذخیره گردید',
        max_keywords: 'حداکثر 10 کلیدواژه قابل تعریف می باشد',
        max_information_rows: 'حداکثر 20 سطر مشخصات قابل تعریف می باشد',
        website_required: 'لطفا وبسایت خود را وارد نمایید',
        work_type_required: 'لطفا درباره کسب و کار خودتان توضیح دهید',
        keywords_required: 'لیست کلیدواژه ها نمی تواند خالی باشد',
        description_required: 'لطفا توضیحات و نکات پروژه خود را وارد نمایید',
        seo_saved: 'پروژه ی سئوی شما با موفقیت ذخیره گردید',
        article_title_required: 'لطفا عنوان مقاله را وارد نمایید',
        article_body_required: 'لطفا توضیحات مقاله را وارد نمایید',
        article_saved: 'مقاله شما با موفقیت ذخیره گردید',
        product_title_required: 'لطفا عنوان مخصوال را وارد نمایید',
        product_price_required: 'لطفا قیمت محصول را وارد نمایید',
        product_price_not_valid: 'قیمت محصول صحیح وارد نشده است',
        product_description_required: 'لطفا توضیحات محصول را وارد نمایید',
        product_saved: 'محصول شما با موفقیت ذخیره گردید',
        website_template_not_selected: 'لطفا قالب وبسایت خود را انتخاب نمایید',
        website_content_saved: 'فرم محتوای وبسایت با موفقیت ثبت گردید',

    }
};